# Generated by Django 3.2.5 on 2021-07-09 22:37

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ABSDataCache',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('size_in_bytes', models.IntegerField()),
                ('status', models.TextField()),
                ('tag', models.TextField()),
                ('dataframe_format', models.TextField()),
                ('field', models.TextField()),
                ('last_updated', models.DateTimeField()),
                ('market', models.TextField()),
                ('n_days', models.IntegerField()),
                ('n_stocks', models.IntegerField()),
                ('sha256', models.TextField()),
                ('scope', models.TextField()),
                ('dataframe', models.BinaryField()),
            ],
            options={
                'db_table': 'abs_data_cache',
            },
        ),
        migrations.CreateModel(
            name='ABSDataflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abs_id', models.TextField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ABSHeadlineDataRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataflow', models.TextField()),
                ('idx', models.IntegerField()),
                ('time_period', models.TextField()),
                ('variable', models.TextField()),
                ('val', models.TextField()),
            ],
            options={
                'db_table': 'abs_headline_data',
            },
        ),
        migrations.CreateModel(
            name='ABSInvertedIndex',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False)),
                ('min_date', models.DateTimeField()),
                ('max_date', models.DateTimeField()),
                ('n_attributes', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('tag', models.TextField()),
                ('dataset', models.TextField()),
                ('name', models.TextField()),
                ('scope', models.TextField()),
            ],
            options={
                'db_table': 'abs_inverted_index',
            },
        ),
    ]
