# Generated by Django 3.2.5 on 2021-07-09 22:37

from django.db import migrations, models
import djongo.models.fields
import djongo.models.json
import worldbank.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorldBankCountry',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False)),
                ('country_code', models.TextField()),
                ('name', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'World Bank Countries',
                'db_table': 'world_bank_countries',
            },
        ),
        migrations.CreateModel(
            name='WorldBankDataCache',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('size_in_bytes', models.IntegerField()),
                ('status', models.TextField()),
                ('tag', models.TextField()),
                ('dataframe_format', models.TextField()),
                ('field', models.TextField()),
                ('last_updated', models.DateTimeField()),
                ('market', models.TextField()),
                ('n_days', models.IntegerField()),
                ('n_stocks', models.IntegerField()),
                ('sha256', models.TextField()),
                ('scope', models.TextField()),
                ('dataframe', models.BinaryField()),
            ],
            options={
                'db_table': 'worldbank_data_cache',
            },
        ),
        migrations.CreateModel(
            name='WorldBankIndicators',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False)),
                ('wb_id', models.TextField()),
                ('name', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('unit', models.TextField()),
                ('source', djongo.models.json.JSONField()),
                ('source_note', models.TextField()),
                ('topics', djongo.models.fields.ArrayField(model_container=worldbank.models.WorldBankTopic)),
                ('source_organisation', models.TextField()),
                ('last_successful_data', models.DateTimeField(null=True)),
                ('last_error_when', models.DateTimeField(null=True)),
                ('last_error_msg', models.TextField()),
                ('last_error_type', models.TextField()),
            ],
            options={
                'verbose_name': 'World Bank Metric',
                'verbose_name_plural': 'World Bank Metrics',
                'db_table': 'world_bank_indicators',
            },
        ),
        migrations.CreateModel(
            name='WorldBankInvertedIndex',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False)),
                ('country', models.TextField()),
                ('topic_id', models.IntegerField()),
                ('topic_name', models.TextField()),
                ('n_attributes', models.IntegerField()),
                ('last_updated', models.DateTimeField()),
                ('tag', models.TextField()),
                ('indicator_id', models.TextField()),
                ('indicator_name', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'World Bank Inverted Indexes',
                'db_table': 'world_bank_inverted_index',
            },
        ),
        migrations.CreateModel(
            name='WorldBankTopic',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('topic', models.TextField()),
                ('source_note', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'world_bank_topics',
            },
        ),
    ]
