# Generated by Django 3.2.5 on 2021-07-09 22:37

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ECBDataCache',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False)),
                ('size_in_bytes', models.IntegerField()),
                ('status', models.TextField()),
                ('tag', models.TextField()),
                ('dataframe_format', models.TextField()),
                ('field', models.TextField()),
                ('last_updated', models.DateTimeField()),
                ('market', models.TextField()),
                ('n_days', models.IntegerField()),
                ('n_stocks', models.IntegerField()),
                ('sha256', models.TextField()),
                ('scope', models.TextField()),
                ('dataframe', models.BinaryField()),
            ],
            options={
                'verbose_name': 'ECB Data Cache',
                'verbose_name_plural': 'ECB Data Cache',
                'db_table': 'ecb_data_cache',
            },
        ),
        migrations.CreateModel(
            name='ECBFlow',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='flow_name')),
                ('description', models.TextField(db_column='flow_descr')),
                ('is_test_data', models.BooleanField()),
                ('last_updated', models.DateTimeField()),
                ('prepared', models.DateTimeField()),
                ('sender', models.TextField()),
                ('source', models.TextField()),
                ('data_available', models.BooleanField()),
            ],
            options={
                'verbose_name': 'ECB Flow',
                'verbose_name_plural': 'ECB Flow',
                'db_table': 'ecb_flow_index',
            },
        ),
        migrations.CreateModel(
            name='ECBMetadata',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False)),
                ('metadata_type', models.TextField(db_column='metadata_type')),
                ('flow', models.TextField(db_column='flow_name')),
                ('code', models.TextField(db_column='item_name')),
                ('column_name', models.TextField(db_column='codelist_name')),
                ('printable_code', models.TextField(db_column='item_value')),
            ],
            options={
                'verbose_name': 'ECB Metadata',
                'verbose_name_plural': 'ECB Metadata',
                'db_table': 'ecb_metadata_index',
            },
        ),
    ]
